/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moinhomultiplayer;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Ruhan Conceição
 */
public class FrameMoinho extends javax.swing.JFrame {

    /**
     * Creates new form FrameMoinho
     */
    public FrameMoinho() {
        initComponents();
    }

    public JLabel getQuemJoga() {
        return quemJoga;
    }

    
    
    public JLabel getMensagensLabel() {
        return jLabel_Mensagens;
    }
    
    public JButton getjButton3HvsH() {
        return jButton3HvsH;
    }

    public JButton getjButtonHvsPC() {
        return jButtonHvsPC;
    }

    public JButton getjButtonPCvsPC() {
        return jButtonPCvsPC;
    }

    public JButton getjButton_1A() {
        return jButton_1A;
    }

    public JButton getjButton_1D() {
        return jButton_1D;
    }

    public JButton getjButton_1G() {
        return jButton_1G;
    }

    public JButton getjButton_2B() {
        return jButton_2B;
    }

    public JButton getjButton_2D() {
        return jButton_2D;
    }

    public JButton getjButton_2F() {
        return jButton_2F;
    }

    public JButton getjButton_3C() {
        return jButton_3C;
    }

    public JButton getjButton_3D() {
        return jButton_3D;
    }

    public JButton getjButton_3E() {
        return jButton_3E;
    }

    public JButton getjButton_4A() {
        return jButton_4A;
    }

    public JButton getjButton_4B() {
        return jButton_4B;
    }

    public JButton getjButton_4C() {
        return jButton_4C;
    }

    public JButton getjButton_4E() {
        return jButton_4E;
    }

    public JButton getjButton_4F() {
        return jButton_4F;
    }

    public JButton getjButton_4G() {
        return jButton_4G;
    }

    public JButton getjButton_5C() {
        return jButton_5C;
    }

    public JButton getjButton_5D() {
        return jButton_5D;
    }

    public JButton getjButton_5E() {
        return jButton_5E;
    }

    public JButton getjButton_6B() {
        return jButton_6B;
    }

    public JButton getjButton_6D() {
        return jButton_6D;
    }

    public JButton getjButton_6F() {
        return jButton_6F;
    }

    public JButton getjButton_7A() {
        return jButton_7A;
    }

    public JButton getjButton_7D() {
        return jButton_7D;
    }

    public JButton getjButton_7G() {
        return jButton_7G;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPCvsPC = new javax.swing.JButton();
        jButtonHvsPC = new javax.swing.JButton();
        jButton3HvsH = new javax.swing.JButton();
        jButton_1A = new javax.swing.JButton();
        jButton_7A = new javax.swing.JButton();
        jButton_4A = new javax.swing.JButton();
        jButton_4G = new javax.swing.JButton();
        jButton_6D = new javax.swing.JButton();
        jButton_7G = new javax.swing.JButton();
        jButton_1G = new javax.swing.JButton();
        jButton_1D = new javax.swing.JButton();
        jButton_2F = new javax.swing.JButton();
        jButton_3E = new javax.swing.JButton();
        jButton_6F = new javax.swing.JButton();
        jButton_4E = new javax.swing.JButton();
        jButton_2D = new javax.swing.JButton();
        jButton_3D = new javax.swing.JButton();
        jButton_2B = new javax.swing.JButton();
        jButton_4B = new javax.swing.JButton();
        jButton_6B = new javax.swing.JButton();
        jButton_4F = new javax.swing.JButton();
        jButton_7D = new javax.swing.JButton();
        jButton_5E = new javax.swing.JButton();
        jButton_5D = new javax.swing.JButton();
        jButton_5C = new javax.swing.JButton();
        jButton_3C = new javax.swing.JButton();
        jButton_4C = new javax.swing.JButton();
        jLabelN7 = new javax.swing.JLabel();
        jLabelN6 = new javax.swing.JLabel();
        jLabelN5 = new javax.swing.JLabel();
        jLabelN4 = new javax.swing.JLabel();
        jLabelN3 = new javax.swing.JLabel();
        jLabelN2 = new javax.swing.JLabel();
        jLabelN1 = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jLabelD = new javax.swing.JLabel();
        jLabelE = new javax.swing.JLabel();
        jLabelF = new javax.swing.JLabel();
        jLabelG = new javax.swing.JLabel();
        jLabel_Mensagens = new javax.swing.JLabel();
        quemJoga = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(647, 487));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPCvsPC.setText("PC vs PC");
        jButtonPCvsPC.setMaximumSize(new java.awt.Dimension(115, 23));
        jButtonPCvsPC.setMinimumSize(new java.awt.Dimension(115, 23));
        jButtonPCvsPC.setPreferredSize(new java.awt.Dimension(115, 23));
        jButtonPCvsPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPCvsPCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPCvsPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 450, 140, 20));

        jButtonHvsPC.setText("Human vs PC");
        jButtonHvsPC.setMaximumSize(new java.awt.Dimension(115, 23));
        jButtonHvsPC.setMinimumSize(new java.awt.Dimension(115, 23));
        jButtonHvsPC.setPreferredSize(new java.awt.Dimension(115, 23));
        jButtonHvsPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHvsPCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHvsPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 420, 140, 20));

        jButton3HvsH.setText("Human vs Human");
        jButton3HvsH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3HvsHActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3HvsH, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 390, 140, 20));

        jButton_1A.setRolloverEnabled(false);
        jButton_1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1AActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 442, 20, 20));

        jButton_7A.setFocusable(false);
        jButton_7A.setRolloverEnabled(false);
        jButton_7A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7AActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_7A, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 158, 20, 20));

        jButton_4A.setFocusable(false);
        jButton_4A.setRolloverEnabled(false);
        jButton_4A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4AActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 299, 20, 20));

        jButton_4G.setRolloverEnabled(false);
        jButton_4G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4GActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_4G, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 299, 20, 20));

        jButton_6D.setRolloverEnabled(false);
        jButton_6D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6DActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_6D, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 204, 20, 20));

        jButton_7G.setRolloverEnabled(false);
        jButton_7G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7GActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_7G, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 158, 20, 20));

        jButton_1G.setRolloverEnabled(false);
        jButton_1G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1GActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_1G, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 442, 20, 20));

        jButton_1D.setRolloverEnabled(false);
        jButton_1D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1DActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_1D, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 442, 20, 20));

        jButton_2F.setRolloverEnabled(false);
        jButton_2F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2FActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_2F, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 395, 20, 20));

        jButton_3E.setRolloverEnabled(false);
        jButton_3E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3EActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_3E, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 346, 20, 20));

        jButton_6F.setRolloverEnabled(false);
        jButton_6F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6FActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_6F, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 204, 20, 20));

        jButton_4E.setRolloverEnabled(false);
        jButton_4E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4EActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_4E, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 299, 20, 20));

        jButton_2D.setRolloverEnabled(false);
        jButton_2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2DActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 395, 20, 20));

        jButton_3D.setRolloverEnabled(false);
        jButton_3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3DActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 346, 20, 20));

        jButton_2B.setRolloverEnabled(false);
        jButton_2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2BActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 395, 20, 20));

        jButton_4B.setRolloverEnabled(false);
        jButton_4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4BActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 299, 20, 20));

        jButton_6B.setRolloverEnabled(false);
        jButton_6B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6BActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_6B, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 204, 20, 20));

        jButton_4F.setRolloverEnabled(false);
        jButton_4F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4FActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_4F, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 299, 20, 20));

        jButton_7D.setRolloverEnabled(false);
        jButton_7D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7DActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_7D, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 158, 20, 20));

        jButton_5E.setRolloverEnabled(false);
        jButton_5E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5EActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_5E, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 251, 20, 20));

        jButton_5D.setRolloverEnabled(false);
        jButton_5D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5DActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_5D, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 251, 20, 20));

        jButton_5C.setRolloverEnabled(false);
        jButton_5C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5CActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_5C, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 251, 20, 20));

        jButton_3C.setRolloverEnabled(false);
        jButton_3C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3CActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_3C, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 346, 20, 20));

        jButton_4C.setRolloverEnabled(false);
        jButton_4C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4CActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_4C, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 299, 20, 20));

        jLabelN7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelN7.setText("7");
        jLabelN7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 161, 20, -1));

        jLabelN6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelN6.setText("6");
        jLabelN6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 207, 20, -1));

        jLabelN5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelN5.setText("5");
        jLabelN5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 253, 20, -1));

        jLabelN4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelN4.setText("4");
        jLabelN4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 303, 20, -1));

        jLabelN3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelN3.setText("3");
        jLabelN3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 349, 20, -1));

        jLabelN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelN2.setText("2");
        jLabelN2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 397, 20, -1));

        jLabelN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelN1.setText("1");
        jLabelN1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 446, 20, -1));

        jLabelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelA.setText("a");
        getContentPane().add(jLabelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 465, 20, -1));

        jLabelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelB.setText("b");
        getContentPane().add(jLabelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 465, 20, -1));

        jLabelC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelC.setText("c");
        getContentPane().add(jLabelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 465, 20, -1));

        jLabelD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelD.setText("d");
        getContentPane().add(jLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 465, 20, -1));

        jLabelE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelE.setText("e");
        getContentPane().add(jLabelE, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 465, 20, -1));

        jLabelF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelF.setText("f");
        getContentPane().add(jLabelF, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 465, 20, -1));

        jLabelG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelG.setText("g");
        getContentPane().add(jLabelG, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 465, 20, -1));

        jLabel_Mensagens.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_Mensagens.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mensagens.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Mensagens.setText("Mensagens");
        getContentPane().add(jLabel_Mensagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 161, 140, -1));

        quemJoga.setBackground(new java.awt.Color(255, 255, 255));
        quemJoga.setText("A");
        quemJoga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(quemJoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 300, 10, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moinhomultiplayer/Imagem1-Reduzido.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHvsPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHvsPCActionPerformed
        // TODO add your handling code here:
        Game.setJogadores(TipoJogadores.HUMANvsPC);
    }//GEN-LAST:event_jButtonHvsPCActionPerformed

    private void jButton_4AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4AActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(0, 1, 0);
    }//GEN-LAST:event_jButton_4AActionPerformed

    private void jButton_4FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4FActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(1, 1, 2);
    }//GEN-LAST:event_jButton_4FActionPerformed

    private void jButton_7DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7DActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(0, 0, 1);
    }//GEN-LAST:event_jButton_7DActionPerformed

    private void jButton3HvsHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3HvsHActionPerformed
        Game.setJogadores(TipoJogadores.HUMANvsHUMAN);
    }//GEN-LAST:event_jButton3HvsHActionPerformed

    private void jButtonPCvsPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPCvsPCActionPerformed
        // TODO add your handling code here:
        Game.setJogadores(TipoJogadores.PCvsPC);
    }//GEN-LAST:event_jButtonPCvsPCActionPerformed

    private void jButton_1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1AActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(0, 2, 0);
    }//GEN-LAST:event_jButton_1AActionPerformed

    private void jButton_7AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7AActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(0, 0, 0);
    }//GEN-LAST:event_jButton_7AActionPerformed

    private void jButton_7GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7GActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(0, 0, 2);
    }//GEN-LAST:event_jButton_7GActionPerformed

    private void jButton_4GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4GActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(0, 1, 2);
    }//GEN-LAST:event_jButton_4GActionPerformed

    private void jButton_1DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1DActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(0, 2, 1);
    }//GEN-LAST:event_jButton_1DActionPerformed

    private void jButton_1GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1GActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(0, 2, 2);
    }//GEN-LAST:event_jButton_1GActionPerformed

    private void jButton_6BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6BActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(1, 0, 0);
    }//GEN-LAST:event_jButton_6BActionPerformed

    private void jButton_6DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6DActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(1, 0, 1);
    }//GEN-LAST:event_jButton_6DActionPerformed

    private void jButton_6FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6FActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(1, 0, 2);
    }//GEN-LAST:event_jButton_6FActionPerformed

    private void jButton_4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4BActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(1, 1, 0);
    }//GEN-LAST:event_jButton_4BActionPerformed

    private void jButton_2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2BActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(1, 2, 0);
    }//GEN-LAST:event_jButton_2BActionPerformed

    private void jButton_2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2DActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(1, 2, 1);
    }//GEN-LAST:event_jButton_2DActionPerformed

    private void jButton_2FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2FActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(1, 2, 2);
    }//GEN-LAST:event_jButton_2FActionPerformed

    private void jButton_5DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5DActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(2, 0, 1);
    }//GEN-LAST:event_jButton_5DActionPerformed

    private void jButton_5CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5CActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(2, 0, 0);
    }//GEN-LAST:event_jButton_5CActionPerformed

    private void jButton_5EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5EActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(2, 0, 2);
    }//GEN-LAST:event_jButton_5EActionPerformed

    private void jButton_4CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4CActionPerformed
        // TODO add your handling code here:
        
        Game.botaoPressionado(2, 1, 0);
    }//GEN-LAST:event_jButton_4CActionPerformed

    private void jButton_4EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4EActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(2, 1, 2);
    }//GEN-LAST:event_jButton_4EActionPerformed

    private void jButton_3CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3CActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(2, 2, 0);
    }//GEN-LAST:event_jButton_3CActionPerformed

    private void jButton_3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3DActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(2, 2, 1);
    }//GEN-LAST:event_jButton_3DActionPerformed

    private void jButton_3EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3EActionPerformed
        // TODO add your handling code here:
        Game.botaoPressionado(2, 2, 2);
    }//GEN-LAST:event_jButton_3EActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3HvsH;
    private javax.swing.JButton jButtonHvsPC;
    private javax.swing.JButton jButtonPCvsPC;
    private javax.swing.JButton jButton_1A;
    private javax.swing.JButton jButton_1D;
    private javax.swing.JButton jButton_1G;
    private javax.swing.JButton jButton_2B;
    private javax.swing.JButton jButton_2D;
    private javax.swing.JButton jButton_2F;
    private javax.swing.JButton jButton_3C;
    private javax.swing.JButton jButton_3D;
    private javax.swing.JButton jButton_3E;
    private javax.swing.JButton jButton_4A;
    private javax.swing.JButton jButton_4B;
    private javax.swing.JButton jButton_4C;
    private javax.swing.JButton jButton_4E;
    private javax.swing.JButton jButton_4F;
    private javax.swing.JButton jButton_4G;
    private javax.swing.JButton jButton_5C;
    private javax.swing.JButton jButton_5D;
    private javax.swing.JButton jButton_5E;
    private javax.swing.JButton jButton_6B;
    private javax.swing.JButton jButton_6D;
    private javax.swing.JButton jButton_6F;
    private javax.swing.JButton jButton_7A;
    private javax.swing.JButton jButton_7D;
    private javax.swing.JButton jButton_7G;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelD;
    private javax.swing.JLabel jLabelE;
    private javax.swing.JLabel jLabelF;
    private javax.swing.JLabel jLabelG;
    private javax.swing.JLabel jLabelN1;
    private javax.swing.JLabel jLabelN2;
    private javax.swing.JLabel jLabelN3;
    private javax.swing.JLabel jLabelN4;
    private javax.swing.JLabel jLabelN5;
    private javax.swing.JLabel jLabelN6;
    private javax.swing.JLabel jLabelN7;
    private javax.swing.JLabel jLabel_Mensagens;
    private javax.swing.JLabel quemJoga;
    // End of variables declaration//GEN-END:variables
}
